# -*- coding: utf-8 -*-
"""TDSweek8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YoxS1ypr-P1a1Wgk1JVUHJAcvvyp2XTO
"""

pip install streamlit

import streamlit as st

def largest_number(a, b, c):
    if a > b and a > c:
        return a
    elif b > a and b > c:
        return b
    else:
        return c

st.title("Find the largest among three numbers")
st.write("Enter three numbers below")

a = st.number_input("Enter the first number:")
b = st.number_input("Enter the second number:")
c = st.number_input("Enter the third number:")

if st.button("Find Largest Number"):
    result = largest_number(a, b, c)
    st.write("The largest number is:", result)



